version: '3'

services:
  app:
    container_name: app
    image: node:20
    ports:
      - '8081:3000'
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app
    command: npm run start:dev
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7
    restart: always
